import {
  Baby,
  Briefcase,
  Building2,
  Camera,
  Car,
  Dumbbell,
  Gem,
  Gift,
  GraduationCap,
  Heart,
  Home,
  Laptop,
  Music,
  Palmtree,
  PiggyBank,
  Plane,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Star,
  Trophy,
  Utensils,
  Wallet,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const PIGGY_BANK_ICONS: { name: string; Icon: LucideIcon }[] = [
  { name: "piggy-bank", Icon: PiggyBank },
  { name: "plane", Icon: Plane },
  { name: "home", Icon: Home },
  { name: "car", Icon: Car },
  { name: "graduation-cap", Icon: GraduationCap },
  { name: "gift", Icon: Gift },
  { name: "shield-check", Icon: ShieldCheck },
  { name: "heart", Icon: Heart },
  { name: "baby", Icon: Baby },
  { name: "briefcase", Icon: Briefcase },
  { name: "laptop", Icon: Laptop },
  { name: "smartphone", Icon: Smartphone },
  { name: "camera", Icon: Camera },
  { name: "music", Icon: Music },
  { name: "dumbbell", Icon: Dumbbell },
  { name: "utensils", Icon: Utensils },
  { name: "shopping-bag", Icon: ShoppingBag },
  { name: "palmtree", Icon: Palmtree },
  { name: "building-2", Icon: Building2 },
  { name: "wrench", Icon: Wrench },
  { name: "wallet", Icon: Wallet },
  { name: "star", Icon: Star },
  { name: "trophy", Icon: Trophy },
  { name: "gem", Icon: Gem },
];

export const DEFAULT_PIGGY_BANK_ICON = "piggy-bank";

export const PIGGY_BANK_ICON_MAP: Record<string, LucideIcon> =
  Object.fromEntries(PIGGY_BANK_ICONS.map(({ name, Icon }) => [name, Icon]));
