import {
  Baby,
  Briefcase,
  Building2,
  Camera,
  Car,
  Dumbbell,
  Gem,
  Gift,
  GraduationCap,
  Heart,
  Home,
  Laptop,
  Music,
  Palmtree,
  PiggyBank,
  Plane,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Star,
  Trophy,
  Utensils,
  Wallet,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const PIGGY_BANK_ICONS: { name: string; label: string; Icon: LucideIcon }[] = [
  { name: "piggy-bank", label: "Cofrinho", Icon: PiggyBank },
  { name: "plane", label: "Viagem", Icon: Plane },
  { name: "home", label: "Casa", Icon: Home },
  { name: "car", label: "Carro", Icon: Car },
  { name: "graduation-cap", label: "Educação", Icon: GraduationCap },
  { name: "gift", label: "Presente", Icon: Gift },
  { name: "shield-check", label: "Proteção", Icon: ShieldCheck },
  { name: "heart", label: "Saúde", Icon: Heart },
  { name: "baby", label: "Bebê", Icon: Baby },
  { name: "briefcase", label: "Trabalho", Icon: Briefcase },
  { name: "laptop", label: "Notebook", Icon: Laptop },
  { name: "smartphone", label: "Celular", Icon: Smartphone },
  { name: "camera", label: "Fotografia", Icon: Camera },
  { name: "music", label: "Música", Icon: Music },
  { name: "dumbbell", label: "Academia", Icon: Dumbbell },
  { name: "utensils", label: "Alimentação", Icon: Utensils },
  { name: "shopping-bag", label: "Compras", Icon: ShoppingBag },
  { name: "palmtree", label: "Férias", Icon: Palmtree },
  { name: "building-2", label: "Imóvel", Icon: Building2 },
  { name: "wrench", label: "Manutenção", Icon: Wrench },
  { name: "wallet", label: "Carteira", Icon: Wallet },
  { name: "star", label: "Meta especial", Icon: Star },
  { name: "trophy", label: "Conquista", Icon: Trophy },
  { name: "gem", label: "Luxo", Icon: Gem },
];

export const DEFAULT_PIGGY_BANK_ICON = "piggy-bank";

export const PIGGY_BANK_ICON_MAP: Record<string, LucideIcon> =
  Object.fromEntries(PIGGY_BANK_ICONS.map(({ name, Icon }) => [name, Icon]));
